<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTgZELJs\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTgZELJs/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTgZELJs.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTgZELJs\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTgZELJs\App_KernelProdContainer([
    'container.build_hash' => 'TgZELJs',
    'container.build_id' => 'eb29601e',
    'container.build_time' => 1677017944,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTgZELJs');
