<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'mainPageAdmin' => [[], ['_controller' => 'App\\Controller\\Admin\\mainPageController::index'], [], [['text', '/admin/']], [], [], []],
    'mainPageParent' => [[], ['_controller' => 'App\\Controller\\Parent\\mainPageController::index'], [], [['text', '/parent/']], [], [], []],
    'appLogin' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'appLogout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'mainAbsenceStudent' => [[], ['_controller' => 'App\\Controller\\Student\\absencePageController::index'], [], [['text', '/student/absence/']], [], [], []],
    'mainPageStudent' => [[], ['_controller' => 'App\\Controller\\Student\\mainPageController::index'], [], [['text', '/student/']], [], [], []],
    'mainMarksStudent' => [[], ['_controller' => 'App\\Controller\\Student\\marksPageController::index'], [], [['text', '/student/marks/']], [], [], []],
    'marksStudentId' => [['id'], ['_controller' => 'App\\Controller\\Student\\marksPageController::marks'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/student/marks']], [], [], []],
    'timeTableStudent' => [[], ['_controller' => 'App\\Controller\\Student\\timeTablePageController::index'], [], [['text', '/student/timetable']], [], [], []],
    'mainPageTeacher' => [[], ['_controller' => 'App\\Controller\\Teacher\\mainPageController::index'], [], [['text', '/teacher/']], [], [], []],
    'marksMainPageTeacher' => [[], ['_controller' => 'App\\Controller\\Teacher\\marksPageController::marks'], [], [['text', '/teacher/marks']], [], [], []],
    'marksClassPageTeacher' => [['id'], ['_controller' => 'App\\Controller\\Teacher\\marksPageController::marksClass'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teacher/marks/class']], [], [], []],
    'marksAddClass' => [['id'], ['_controller' => 'App\\Controller\\Teacher\\marksPageController::addMarksClass'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/teacher/marks/class/add']], [], [], []],
    'mainSite' => [[], ['_controller' => 'App\\Controller\\mainSiteController::mainSite'], [], [['text', '/']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\mainSiteController::contactSite'], [], [['text', '/contact']], [], [], []],
];
