<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Absence__CLASSMETADATA__' => 0,
'App__Entity__User__CLASSMETADATA__' => 1,
'App__Entity__Marks__CLASSMETADATA__' => 2,
'App__Entity__SchoolSubject__CLASSMETADATA__' => 3,
'App__Entity__Teacher__CLASSMETADATA__' => 4,
'App__Entity__HoursOfClassesAndBreaks__CLASSMETADATA__' => 5,
'App__Entity__Student__CLASSMETADATA__' => 6,
'App__Entity__SchoolClass__CLASSMETADATA__' => 7,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Absence',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Absence',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\AbsenceRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'students' => [
                            'fieldName' => 'students',
                            'type' => 'array',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'students',
                        ],
                        'date' => [
                            'fieldName' => 'date',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'date',
                        ],
                        'ts' => [
                            'fieldName' => 'ts',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'ts',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'students' => 'students',
                        'date' => 'date',
                        'ts' => 'ts',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'students' => 'students',
                        'date' => 'date',
                        'ts' => 'ts',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'absence',
                    ],
                ],
                'associationMappings' => [
                    [
                        'fk_id_school_lesson' => [
                            'fieldName' => 'fk_id_school_lesson',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_id_school_lesson_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\SchoolSubject',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Absence',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_id_school_lesson_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_id_school_lesson_id' => 'fk_id_school_lesson_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_id_school_lesson_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'fk_teacher_id' => [
                            'fieldName' => 'fk_teacher_id',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_teacher_id_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Teacher',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Absence',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_teacher_id_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_teacher_id_id' => 'fk_teacher_id_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_teacher_id_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'absence_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'absence_id_seq',
            ],
        ]
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\User',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'email' => [
                            'fieldName' => 'email',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 180,
                            'unique' => true,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'email',
                        ],
                        'roles' => [
                            'fieldName' => 'roles',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'roles',
                        ],
                        'password' => [
                            'fieldName' => 'password',
                            'type' => 'string',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'password',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'email' => 'email',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'quoted' => true,
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'user_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                        'quoted' => true,
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => '"user_id_seq"',
            ],
        ]
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Marks',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Marks',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\MarksRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'mark' => [
                            'fieldName' => 'mark',
                            'type' => 'float',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'mark',
                        ],
                        'weight' => [
                            'fieldName' => 'weight',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'weight',
                        ],
                        'ts' => [
                            'fieldName' => 'ts',
                            'type' => 'datetime',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'ts',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'mark' => 'mark',
                        'weight' => 'weight',
                        'ts' => 'ts',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'mark' => 'mark',
                        'weight' => 'weight',
                        'ts' => 'ts',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'marks',
                    ],
                ],
                'associationMappings' => [
                    [
                        'fk_id_user_teacher' => [
                            'fieldName' => 'fk_id_user_teacher',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_id_user_teacher_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Teacher',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Marks',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_id_user_teacher_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_id_user_teacher_id' => 'fk_id_user_teacher_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_id_user_teacher_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'fk_id_user_student' => [
                            'fieldName' => 'fk_id_user_student',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_id_user_student_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\Student',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Marks',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_id_user_student_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_id_user_student_id' => 'fk_id_user_student_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_id_user_student_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                        'fk_id_schoolSubject' => [
                            'fieldName' => 'fk_id_schoolSubject',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_id_school_subject_id',
                                    'unique' => false,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => null,
                            'targetEntity' => 'App\\Entity\\SchoolSubject',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Marks',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_id_school_subject_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_id_school_subject_id' => 'fk_id_school_subject_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_id_school_subject_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'marks_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'marks_id_seq',
            ],
        ]
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\SchoolSubject',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\SchoolSubject',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SchoolSubjectRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Name' => [
                            'fieldName' => 'Name',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'name',
                        ],
                        'Shortcut' => [
                            'fieldName' => 'Shortcut',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 10,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'shortcut',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'shortcut' => 'Shortcut',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Shortcut' => 'shortcut',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'school_subject',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'school_subject_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'school_subject_id_seq',
            ],
        ]
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Teacher',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Teacher',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TeacherRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Name' => [
                            'fieldName' => 'Name',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'name',
                        ],
                        'Surname' => [
                            'fieldName' => 'Surname',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'surname',
                        ],
                        'Telephone' => [
                            'fieldName' => 'Telephone',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 15,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'telephone',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'surname' => 'Surname',
                        'telephone' => 'Telephone',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Surname' => 'surname',
                        'Telephone' => 'telephone',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'teacher',
                    ],
                ],
                'associationMappings' => [
                    [
                        'fk_id_user' => [
                            'fieldName' => 'fk_id_user',
                            'targetEntity' => 'App\\Entity\\User',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_id_user_id',
                                    'unique' => true,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'mappedBy' => null,
                            'inversedBy' => null,
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 1,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Teacher',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_id_user_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_id_user_id' => 'fk_id_user_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_id_user_id',
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'teacher_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'teacher_id_seq',
            ],
        ]
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\HoursOfClassesAndBreaks',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\HoursOfClassesAndBreaks',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\HoursOfClassesAndBreaksRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'timesJson' => [
                            'fieldName' => 'timesJson',
                            'type' => 'json',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'times_json',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'times_json' => 'timesJson',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'timesJson' => 'times_json',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'hours_of_classes_and_breaks',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'hours_of_classes_and_breaks_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'hours_of_classes_and_breaks_id_seq',
            ],
        ]
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Student',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Student',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\StudentRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Name' => [
                            'fieldName' => 'Name',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'name',
                        ],
                        'Surname' => [
                            'fieldName' => 'Surname',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'surname',
                        ],
                        'Telephone' => [
                            'fieldName' => 'Telephone',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 15,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'telephone',
                        ],
                        'Email' => [
                            'fieldName' => 'Email',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 255,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'email',
                        ],
                        'NumberIdentGoverment' => [
                            'fieldName' => 'NumberIdentGoverment',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 32,
                            'unique' => false,
                            'nullable' => true,
                            'precision' => null,
                            'columnName' => 'number_ident_goverment',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'Name',
                        'surname' => 'Surname',
                        'telephone' => 'Telephone',
                        'email' => 'Email',
                        'number_ident_goverment' => 'NumberIdentGoverment',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Name' => 'name',
                        'Surname' => 'surname',
                        'Telephone' => 'telephone',
                        'Email' => 'email',
                        'NumberIdentGoverment' => 'number_ident_goverment',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'student',
                    ],
                ],
                'associationMappings' => [
                    [
                        'fk_id_user' => [
                            'fieldName' => 'fk_id_user',
                            'targetEntity' => 'App\\Entity\\User',
                            'joinColumns' => [
                                [
                                    'name' => 'fk_id_user_id',
                                    'unique' => true,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'mappedBy' => null,
                            'inversedBy' => null,
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 1,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Student',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'fk_id_user_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'fk_id_user_id' => 'fk_id_user_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'fk_id_user_id',
                            ],
                        ],
                        'class' => [
                            'fieldName' => 'class',
                            'joinColumns' => [
                                [
                                    'name' => 'class_id',
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'cascade' => [],
                            'inversedBy' => 'students',
                            'targetEntity' => 'App\\Entity\\SchoolClass',
                            'fetch' => 2,
                            'type' => 2,
                            'mappedBy' => null,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\Student',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'class_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'class_id' => 'class_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'class_id',
                            ],
                            'orphanRemoval' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'student_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'student_id_seq',
            ],
        ]
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\SchoolClass',
                ],
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\SchoolClass',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SchoolClassRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => [
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'id' => true,
                            'columnName' => 'id',
                        ],
                        'Level' => [
                            'fieldName' => 'Level',
                            'type' => 'integer',
                            'scale' => null,
                            'length' => null,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'level',
                        ],
                        'symbol' => [
                            'fieldName' => 'symbol',
                            'type' => 'string',
                            'scale' => null,
                            'length' => 10,
                            'unique' => false,
                            'nullable' => false,
                            'precision' => null,
                            'columnName' => 'symbol',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'level' => 'Level',
                        'symbol' => 'symbol',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Level' => 'level',
                        'symbol' => 'symbol',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'school_class',
                    ],
                ],
                'associationMappings' => [
                    [
                        'HeadTeacher' => [
                            'fieldName' => 'HeadTeacher',
                            'targetEntity' => 'App\\Entity\\Teacher',
                            'joinColumns' => [
                                [
                                    'name' => 'head_teacher_id',
                                    'unique' => true,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'mappedBy' => null,
                            'inversedBy' => null,
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 1,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\SchoolClass',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'head_teacher_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'head_teacher_id' => 'head_teacher_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'head_teacher_id',
                            ],
                        ],
                        'HeadStudent' => [
                            'fieldName' => 'HeadStudent',
                            'targetEntity' => 'App\\Entity\\Student',
                            'joinColumns' => [
                                [
                                    'name' => 'head_student_id',
                                    'unique' => true,
                                    'nullable' => false,
                                    'onDelete' => null,
                                    'columnDefinition' => null,
                                    'referencedColumnName' => 'id',
                                ],
                            ],
                            'mappedBy' => null,
                            'inversedBy' => null,
                            'cascade' => [
                                'persist',
                                'remove',
                            ],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 1,
                            'isOwningSide' => true,
                            'sourceEntity' => 'App\\Entity\\SchoolClass',
                            'isCascadeRemove' => true,
                            'isCascadePersist' => true,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                            'sourceToTargetKeyColumns' => [
                                'head_student_id' => 'id',
                            ],
                            'joinColumnFieldNames' => [
                                'head_student_id' => 'head_student_id',
                            ],
                            'targetToSourceKeyColumns' => [
                                'id' => 'head_student_id',
                            ],
                        ],
                        'students' => [
                            'fieldName' => 'students',
                            'mappedBy' => 'class',
                            'targetEntity' => 'App\\Entity\\Student',
                            'cascade' => [],
                            'orphanRemoval' => false,
                            'fetch' => 2,
                            'type' => 4,
                            'inversedBy' => null,
                            'isOwningSide' => false,
                            'sourceEntity' => 'App\\Entity\\SchoolClass',
                            'isCascadeRemove' => false,
                            'isCascadePersist' => false,
                            'isCascadeRefresh' => false,
                            'isCascadeMerge' => false,
                            'isCascadeDetach' => false,
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'school_class_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
            ],
        ],
        $o[0],
        [
            -1 => [
                'allocationSize' => 1,
                'sequenceName' => 'school_class_id_seq',
            ],
        ]
    );
},

]];
