<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7IZnIU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7IZnIU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7IZnIU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7IZnIU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7IZnIU\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7IZnIU',
    'container.build_id' => '7bd3c37b',
    'container.build_time' => 1682285188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7IZnIU');
