<?php

namespace ContainerTgZELJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainPageController4Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Teacher\mainPageController' shared autowired service.
     *
     * @return \App\Controller\Teacher\mainPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Teacher\\mainPageController'] = $instance = new \App\Controller\Teacher\mainPageController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\Teacher\\mainPageController', $container));

        return $instance;
    }
}
