<?php

namespace ContainerTgZELJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolClassRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SchoolClassRepository' shared autowired service.
     *
     * @return \App\Repository\SchoolClassRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SchoolClassRepository'] = new \App\Repository\SchoolClassRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
