<?php

namespace ContainerTgZELJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolSubjectRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SchoolSubjectRepository' shared autowired service.
     *
     * @return \App\Repository\SchoolSubjectRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SchoolSubjectRepository'] = new \App\Repository\SchoolSubjectRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
