<?php

namespace ContainerTgZELJs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeacherRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TeacherRepository' shared autowired service.
     *
     * @return \App\Repository\TeacherRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TeacherRepository'] = new \App\Repository\TeacherRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
