<?php

namespace ContainerMWdFx2X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_ContainerRepositoryFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.container_repository_factory' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php';

        return $container->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Repository\\AbsenceRepository' => ['privates', 'App\\Repository\\AbsenceRepository', 'getAbsenceRepositoryService', true],
            'App\\Repository\\HoursOfClassesAndBreaksRepository' => ['privates', 'App\\Repository\\HoursOfClassesAndBreaksRepository', 'getHoursOfClassesAndBreaksRepositoryService', true],
            'App\\Repository\\MarksRepository' => ['privates', 'App\\Repository\\MarksRepository', 'getMarksRepositoryService', true],
            'App\\Repository\\SchoolClassRepository' => ['privates', 'App\\Repository\\SchoolClassRepository', 'getSchoolClassRepositoryService', true],
            'App\\Repository\\SchoolSubjectRepository' => ['privates', 'App\\Repository\\SchoolSubjectRepository', 'getSchoolSubjectRepositoryService', true],
            'App\\Repository\\StudentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'App\\Repository\\TeacherRepository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
            'App\\Repository\\UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'App\\Repository\\AbsenceRepository' => '?',
            'App\\Repository\\HoursOfClassesAndBreaksRepository' => '?',
            'App\\Repository\\MarksRepository' => '?',
            'App\\Repository\\SchoolClassRepository' => '?',
            'App\\Repository\\SchoolSubjectRepository' => '?',
            'App\\Repository\\StudentRepository' => '?',
            'App\\Repository\\TeacherRepository' => '?',
            'App\\Repository\\UserRepository' => '?',
        ]));
    }
}
