<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJI5IZcL\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJI5IZcL/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJI5IZcL.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJI5IZcL\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJI5IZcL\App_KernelTestDebugContainer([
    'container.build_hash' => 'JI5IZcL',
    'container.build_id' => 'fa1171f5',
    'container.build_time' => 1682248558,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJI5IZcL');
